/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class FormTiketTravel extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        namaField.putClientProperty("JTextField.placeholderText", "Nama Sesuai KTP");
        nomorhpField.putClientProperty("JTextField.placeholderText", "08xxxxxxxxx");
        getRootPane().setDefaultButton(pesanButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelas = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        namaField = new javax.swing.JTextField();
        nomorhpField = new javax.swing.JTextField();
        kotaCombo = new javax.swing.JComboBox<>();
        ekonomiRadio = new javax.swing.JRadioButton();
        bisnisRadio = new javax.swing.JRadioButton();
        eksekutifRadio = new javax.swing.JRadioButton();
        bagasiCheck = new javax.swing.JCheckBox();
        makanCheck = new javax.swing.JCheckBox();
        asuransiCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaText = new javax.swing.JTextArea();
        namaLabel = new javax.swing.JLabel();
        nomorhpLabel = new javax.swing.JLabel();
        kotaTujuanLabel = new javax.swing.JLabel();
        kelasLabel = new javax.swing.JLabel();
        fasilitanLabel = new javax.swing.JLabel();
        pesanButton = new javax.swing.JButton();
        temaToggle = new javax.swing.JToggleButton();
        catatanLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        namaField.addActionListener(this::namaFieldActionPerformed);

        nomorhpField.addActionListener(this::nomorhpFieldActionPerformed);

        kotaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));
        kotaCombo.addActionListener(this::kotaComboActionPerformed);

        kelas.add(ekonomiRadio);
        ekonomiRadio.setSelected(true);
        ekonomiRadio.setText("Ekonomi");
        ekonomiRadio.addActionListener(this::ekonomiRadioActionPerformed);

        kelas.add(bisnisRadio);
        bisnisRadio.setText("Bisnis");
        bisnisRadio.addActionListener(this::bisnisRadioActionPerformed);

        kelas.add(eksekutifRadio);
        eksekutifRadio.setText("Eksekutif");
        eksekutifRadio.addActionListener(this::eksekutifRadioActionPerformed);

        bagasiCheck.setText("Bagasi");
        bagasiCheck.addActionListener(this::bagasiCheckActionPerformed);

        makanCheck.setText("Makan");
        makanCheck.addActionListener(this::makanCheckActionPerformed);

        asuransiCheck.setText("Asuransi");
        asuransiCheck.addActionListener(this::asuransiCheckActionPerformed);

        areaText.setColumns(20);
        areaText.setRows(3);
        jScrollPane1.setViewportView(areaText);

        namaLabel.setText("Nama");

        nomorhpLabel.setText("Nomor HP");

        kotaTujuanLabel.setText("Kota Tujuan");

        kelasLabel.setText("Kelas");

        fasilitanLabel.setText("Fasilitas Tambahan");

        pesanButton.setText("Pesan");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        temaToggle.setText("Mode Gelap");
        temaToggle.addActionListener(this::temaToggleActionPerformed);

        catatanLabel.setText("Catatan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomorhpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(namaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(kelasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65))
                            .addComponent(kotaTujuanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fasilitanLabel)
                            .addComponent(catatanLabel))
                        .addGap(50, 50, 50)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ekonomiRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bagasiCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bisnisRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(makanCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eksekutifRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(asuransiCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nomorhpField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(namaField)
                                        .addComponent(kotaCombo, 0, 281, Short.MAX_VALUE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(244, 244, 244))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(temaToggle)
                .addGap(18, 18, 18)
                .addComponent(pesanButton)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaLabel)
                    .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorhpLabel)
                    .addComponent(nomorhpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaTujuanLabel)
                    .addComponent(kotaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ekonomiRadio)
                        .addComponent(bisnisRadio)
                        .addComponent(eksekutifRadio))
                    .addComponent(kelasLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asuransiCheck)
                    .addComponent(bagasiCheck)
                    .addComponent(fasilitanLabel)
                    .addComponent(makanCheck))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(catatanLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(temaToggle)
                    .addComponent(pesanButton))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekonomiRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekonomiRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ekonomiRadioActionPerformed

    private void bisnisRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bisnisRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bisnisRadioActionPerformed

    private void makanCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makanCheckActionPerformed

    private void kotaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kotaComboActionPerformed

    private void eksekutifRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eksekutifRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eksekutifRadioActionPerformed

    private void bagasiCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagasiCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bagasiCheckActionPerformed

    private void asuransiCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asuransiCheckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_asuransiCheckActionPerformed

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void temaToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaToggleActionPerformed
        gantiTema(temaToggle.isSelected());
    }//GEN-LAST:event_temaToggleActionPerformed

    private void nomorhpFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomorhpFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomorhpFieldActionPerformed

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
        tampilkanRingkasan();
    }//GEN-LAST:event_pesanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaText;
    private javax.swing.JCheckBox asuransiCheck;
    private javax.swing.JCheckBox bagasiCheck;
    private javax.swing.JRadioButton bisnisRadio;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JRadioButton ekonomiRadio;
    private javax.swing.JRadioButton eksekutifRadio;
    private javax.swing.JLabel fasilitanLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.ButtonGroup kelas;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JComboBox<String> kotaCombo;
    private javax.swing.JLabel kotaTujuanLabel;
    private javax.swing.JCheckBox makanCheck;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField nomorhpField;
    private javax.swing.JLabel nomorhpLabel;
    private javax.swing.JButton pesanButton;
    private javax.swing.JToggleButton temaToggle;
    // End of variables declaration//GEN-END:variables

private void tampilkanRingkasan() {
        String kelas = ekonomiRadio.isSelected() ? "Ekonomi": bisnisRadio.isSelected() ? "Bisnis" :  "Eksekutif";
        List<String> fasilitas = new ArrayList<>();
        for (JCheckBox cb : List.of(bagasiCheck, makanCheck, asuransiCheck)) {
            if (cb.isSelected()) {
                fasilitas.add(cb.getText());
            }
        }
        String pesan = "Nama: " + namaField.getText()
                + "\nNomor HP: " + nomorhpField.getText()
                + "\nKota Tujuan : " + kotaCombo.getSelectedItem()
                + "\nKelas : " + kelas
                + "\nFasilitas Tambahan : " + (fasilitas.isEmpty() ? "-" : String.join(", ", fasilitas))
                + "\nCatatan : " + areaText.getText();
        JOptionPane.showMessageDialog(this, pesan, "Data Pemesanan",
                JOptionPane.INFORMATION_MESSAGE);
    }
private void gantiTema(boolean gelap) {
        if (gelap) {
            FlatDarkLaf.setup();
        } else {
            FlatLightLaf.setup();
        }
        FlatLaf.updateUI(); // terapkan tema baru ke semua jendela yang terbuka
        temaToggle.setText(gelap ? "Mode Terang" : "Mode Gelap");
    }
}
